# Generated by Django 5.1.3 on 2024-11-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description of the task.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed information about the task.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current status of the task.', max_length=20)),
                ('priority', models.IntegerField(default=1, help_text='Priority level of the task, where 1 is the highest priority.')),
                ('due_date', models.DateField(blank=True, help_text='Deadline for completing the task.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated.')),
            ],
        ),
    ]
